// <auto-generated />
namespace FlowerShop3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewTableSales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTableSales));
        
        string IMigrationMetadata.Id
        {
            get { return "202012202238228_NewTable-Sales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
